Models/Cart.cs
// ========================================================
// Cart.cs, 201106 imported from PullCart
// Cartline object also => moved to separate file
// ========================================================
using Microsoft.AspNetCore.SignalR;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.ComponentModel.DataAnnotations;


namespace SHTWIMS03.Models
{
    public class Cart // --------------------------------------------------------------------------
    {
        private List<CartLine> lineCollection = new List<CartLine>();

        public virtual void AddLine(CartLine inCartItem) // p 257 ----------------------
        {
            CartLine line = lineCollection
                .Where(ci => ci.ItemId == inCartItem.ItemId)
                .FirstOrDefault();

            if (line == null)
            {
                lineCollection.Add(inCartItem);
            }
            else
            {
                // what to do if inCartItem already exists?
            }

        } // eo AddItem virtual method ------------------------------------------------------------

        public virtual void RemoveLine(CartLine cartItem) // ------------------------------------
        {
            // called by CartController
            lineCollection.RemoveAll(l => l.ItemId == cartItem.ItemId);

        } // eo RemoveLine virtual method ---------------------------------------------------------

        public virtual void Clear() => lineCollection.Clear();

        // virtual navigation property required by EntityFramework Core
        public virtual IEnumerable<CartLine> Lines => lineCollection;


    } // eo Cart class ----------------------------------------------------------------------------
    
} // eo namespace

Models/CartLine.cs
// ========================================================
// CartLine.cs, 210331
// Author: Russell Fisher
// Recast CartLine type for general purpose
// ========================================================

using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.AspNetCore.Mvc.ModelBinding;
using Microsoft.AspNetCore.Mvc.ModelBinding.Binders;
using Microsoft.Extensions.DependencyInjection; // reqd for GetService method
using SHTWIMS03.Models;
using SHTWIMS03.Areas.Pull.Models;

namespace SHTWIMS03.Models
{

    public partial class CartLine // --------------------------------------------------------
    {
      
        private static IServiceProvider sp;

        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int CartLineId { get; set; }
        [BindNever]
        [ForeignKey("PullHdrId")]
        public int PullHdrId { get; set; }       
        public string ItemId { get; set; }
        public string Description { get; set; }
        public string UoM { get; set; } 
        
        [Required]
        [Range(minimum: 1, maximum: 5000, ErrorMessage = "Please enter a quantity of one or more")]
        public int QtyReq { get; set; }
        
        [Range(minimum: -1, maximum:5000)]
        public int QtyShp { get; set; }
        
        [Required(ErrorMessage = "Please enter a valid date mm/dd/yy")]
        
        public DateTime DateNeeded { get; set; }
        
        public string Comment { get; set; }
        
        public CartLine() // default constructor --------------------------------------------------
        {          
            // empty at present

        } // eo default constructor ---------------------------------------------------------------


        public CartLine(CatalogItem ci) // alt 1 constructor, new Cartline-------------------------
        {
            // upgrade a CatalogItem to a CartLine object
            this.ItemId = ci.ItemId;
            this.Description = ci.Description;
            this.UoM = ci.UoM;
            this.QtyReq = 1;
            this.DateNeeded = DateTime.Today;

        }// eo constructor from CatalogItem--------------------------------------------------------

        public CartLine(PullItem pi)  // alt 2 constructor, update PullItem -----------------------
        {
            // enable Description property
            var ciRepository = sp.GetService<ICatalogItemRepository>();            
            
            // ** convert PullItem to Cartline object
            this.ItemId = pi.ItemId;
            this.Description = ciRepository.CatalogItems.FirstOrDefault(ci => ci.ItemId == pi.ItemId).Description;
            this.UoM = pi.UoM;
            this.QtyReq = pi.QtyRequested;
            this.DateNeeded = pi.DateNeeded;
            this.Comment = pi.Comment;

        } // eo constructor from PullItem ---------------------------------------------------------

    } //eo CartLine class -------------------------------------------------------------------------

} // eo namespace

Models/ViewModels/CartIndexViewModel.cs
// ========================================================
// CartIndexViewModel.cs, 201005 p 267
// Author: Russell Fisher
// 
// ========================================================

using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using SHTWIMS03.Areas.Pull.Models;


namespace SHTWIMS03.Models.ViewModels
{
    public class CartIndexViewModel // ------------------------------------------------------------
    {
        public Cart Cart { get; set; }
        public string ReturnUrl { get; set; }
    } // eo CartIndexViewModel class --------------------------------------------------------------
} // eo namespace

Controllers/CartController.cs
// ========================================================
// CartController.cs, rev 201106
// Author: Russell Fisher
//  routed from 
// ========================================================


using System;
using System.Collections.Generic;
using System.Linq;
using Microsoft.AspNetCore.Mvc;
using SHTWIMS03.Models;
using SHTWIMS03.Models.ViewModels;
using SHTWIMS03.Components;

namespace Areas.SHTWIMS03.Controllers
{
    public class CartController : Controller // ---------------------------------------------------
    {
        private ICatalogItemRepository repository;
        private Cart cart;
        
        // constructor with two service parameters
        public CartController(ICatalogItemRepository repo, Cart cartService) // -------------------------------------
        {
            repository = repo;
            cart = cartService; // p 273

        } // eo constructor -----------------------------------------------------------------------


        public ViewResult Index() // -----------------------------------------------------------
        {
            // request filterString for select list
            return View();
        
        } // eo Index action method ---------------------------------------------------------------


        public ViewResult CiListFiltered(string filterString) // ----------------------------------     
        {
            // this method creates a list based on the incoming filterString parameter
            // - first item is filler object is a place holder for the first item in the filtered list
            CatalogItem filler = new CatalogItem { ItemId = "filler", Description = "Select an item", UoM = "ea" };
            List<CatalogItem> items = new List<CatalogItem>(); // holds search result

            items.Add(filler);

            foreach (CatalogItem iv in repository.CatalogItems)
            {
                if (!String.IsNullOrEmpty(filterString))
                {
                    // convert both items to lower case before comparison
                    if (iv.Description.ToLower().Contains(filterString.ToLower()))
                    {
                        items.Add(iv);
                    }
                }
            }
            return View(items);

        } // eo IClistFilter method ---------------------------------------------------------------
      

        [HttpGet]
        public ViewResult CartLineForm() // ----------------------------------------------------------
        {
            return View();

        } // eo CartLineForm base method -------------------------------------------------------------

        [HttpPost] // it is critical that the parameter has the same name as the <select> tag.
        public IActionResult CartLineForm(string itmSelect) // ----------------------------------------
        {
            // action method to display info from CiFilteredList.itmSelect <select>tag return 
            // from CartForm 

            if (itmSelect != null)
            {
                CartLine cl;
                CatalogItem c = repository.CatalogItems.FirstOrDefault(ci => ci.ItemId == itmSelect);

                // cast CatalogItem object to CartLine type
                cl = new CartLine(c);

                //  call CartForm view to enable input additional information as CartLine 
                return View(cl);
            }
            else
            {
                return RedirectToAction("/Home/Index");
            }

        } //eo CartLineForm  -----------------------------------------------------------------------------       

        public RedirectToActionResult AddToCart(CartLine cartLine, string returnUrl) // ---------------
        {

            if (cartLine != null)
            {
                //Cart cart = GetCart(); // Cart service defined in constructor
                cart.AddLine(cartLine); // call AddLine method of Cart class
                //SaveCart(cart);  comment out p274
            }

            return RedirectToAction("CartIndex", new { returnUrl });

        } // eo AddToCart method ------------------------------------------------------------------

        public ViewResult CartIndex(string returnUrl) // p 267 ----------------------------------------      
        {            
            // View delcares a new CartIndexViewModel and initializes it
            return View(new CartIndexViewModel
            {
                Cart = cart,
                ReturnUrl = returnUrl
            });

        } // eo CartIndex action method ---------------------------------------------------------------

        public RedirectToActionResult RemoveFromCart(CartLine cartItem, string returnUrl) // ----------
        {

            if (cartItem != null)
            {

                //Cart cart = GetCart();
                cart.RemoveLine(cartItem); // Cart service defined in constructor
                // SaveCart(cart); comment out p274
            }

            return RedirectToAction("CartIndex");
            //return RedirectToAction("CartIndex", new { returnUrl });
        } // eo RemoveFromCart method -------------------------------------------------------------


    } // eo CartController ------------------------------------------------------------------------
} // eo namespace

Controllers/PullHdrController.cs
// ========================================================
// PullHdrController.cs, 200909
// Author: Russell Fisher
// completes the Cart implementation
// ========================================================

using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using SHTWIMS02.Models;

namespace SHTWIMS02.Controllers
{
    public class PullHdrController : Controller // ------------------------------------------------
    {
        private IPullHdrRepository repository;
        private Cart cart;

        public PullHdrController(IPullHdrRepository repoService, Cart cartService) // ----------
        {
            repository = repoService;
            cart = cartService;
        
        } // eo constructor with dependency injection ---------------------------------------------

        // method call from CartIndex.cshtml Checkout button
        public ViewResult Checkout() => View("PullHdrForm", new PullHdr());

        public IActionResult Index() // -----------------------------------------------------------
        {
            return View();
        } // eo Index method ----------------------------------------------------------------------

       
        [HttpGet]
        public ViewResult 
            PullHdrForm() // -----------------------------------------------------
        {
            return View();
        } // eo PullHdrForm action method ---------------------------------------------------------

       [HttpPost]
        public IActionResult PullHdrForm(PullHdr pull) // --------------------------------------------
        {
            if (cart.Lines.Count() == 0)
            {
                ModelState.AddModelError("", "Sorry, the cart is empty");
            }
            if (ModelState.IsValid)
            {
                foreach (CartLine line in cart.Lines)
                {
                    // convert CartLine to PullItem
                    pull.PullItems.Add(new PullItem(line));
                }
                repository.SavePullHdr(pull);
                return RedirectToAction(nameof(Completed));                
            }
            else
            {
                // need to decide where to go ?
                return View();
            }
        } // eo PullHdrForm post version ----------------------------------------------------------

        public ViewResult Completed() // ----------------------------------------------------------
        {
            cart.Clear();
            return View();
        } // eo Completed action method -----------------------------------------------------------

    } // eo PullHdrController ---------------------------------------------------------------------
} // eo namespac

Views/Cart/CartIndex.cshtml
@*
    CartIndex.cshtml is a summary listing of all the items in the current Cart
    CartIndexViewModel has two properties: Cart and ReturnUrl
*@
@model CartIndexViewModel

@{
    Layout = "_Layout-Cart";
    ViewData["Title"] ="Cart Index";
    ViewData["pageTitle"] = "Cart Index";
}

<body>
    <div> <!-- this elements is the target of general CSS styling, green dotted border -->
<h3>Current Cart Contents</h3>
<table >
    <thead>
        <tr>
            <th style="width:7rem">Item Id</th>
            <th style="width:18rem">Description</th>
            <th style="width:1rem">Qty</th>
            <th style="width:1rem">UoM</th>
            <th style="width:6rem">Date Rqd</th>
            <th style="width:12rem">Comment</th>
        </tr>

    </thead>
    <!---->
    <tbody>
        @foreach (var line in Model.Cart.Lines)
        {        
            <tr class="tableItem-gradient">
                <td class="text-center">@line.ItemId</td>
                <td class="text-left">@line.Description</td>
                <td class="text-center">@line.QtyReq</td>
                <td class="text-center">@line.UoM</td>
                <td class="text-center">@line.DateNeeded.ToShortDateString()</td>
                <td class="text-left">@line.Comment</td>
                <td>
                    <form asp-action="RemoveFromCart" method="post">
                        <input type="hidden" name="ItemId" value="@line.ItemId" />
                        <input type="hidden" name="returnUrl" value="@Model.ReturnUrl" />
                        <button type="submit" class="btn btn-sm btn-danger">
                            Remove
                        </button>
                    </form>
                </td>
            </tr>
      
        }
    </tbody>

    <!---->
    <tfoot>


    </tfoot>
</table>
<div class="text-center">
    <input type="hidden" name="returnUrl" value="@ViewContext.HttpContext.Request.PathAndQuery()" />

    <!-- <a class="btn btn-primary" href="/Cart/Index">Continue pulls</a> -->
    <a class="btn btn-primary" asp-area="" asp-controller="Cart"  asp-action="Index" >Continue Pulls</a> 
    <a class="btn btn-primary" asp-area="Pull" asp-controller="PullHdr" asp-action="Checkout">Check out</a>
</div>
</div>
</body>

Views/Cart/CartLineForm.cshtml
@*
    ** should be renamed to CartLineForm
     /Views/Cart/CartForm.cshtml
    <link tag - ** the asp-append-version="true" forces browser to use updated CSS file
     see: https://stackoverflow.com/questions/38231739/how-to-disable-browser-cache-in-asp-net-core-rc2
*@
@{
    ViewData["Title"] = "Cart Line";
    ViewData["pageTitle"] = "Cart Line Form";
}
@model CartLine

<body>
    <h3> @ViewBag.AmPm  Welcome to Sam Houston Territory Inventory Management System </h3>

    <form method="post">

        <fieldset>
            <legend>Pull Item - Data Input</legend>
            <ul>

                <li class="form-group">

                    <label asp-for="ItemId">ItemId</label>
                    <input class="form-control" asp-for="ItemId" readonly />
                </li>

                <li>
                    <label asp-for="UoM">UoM</label>
                    <input asp-for="UoM" readonly />
                </li>

                <li>
                    <label asp-for="Description">Description</label>
                    <input asp-for="Description" readonly />
                </li>

                <li>
                    <label asp-for="QtyReq"></label>
                    <input asp-for="QtyReq"  min="1" title="Quantity requested" autofocus required/>
                </li>
                <li>
                    <label asp-for="DateNeeded"></label>
                    <!-- input class="formInputDate" type="date" asp-for="DateNeeded" asp-format="{0:dd-mm-yy}" / -->
                    <input class="formInputDate" type="date" asp-for="DateNeeded" />
                </li>
                <li>
                    <label asp-for="Comment"></label>
                    <textarea asp-for="Comment"></textarea>
                </li>

                <!-- Add To Cart  -->
                <li>
                    <!--
                    <input type="hidden" asp-for="CartLineId" />
                    -->
                    <input type="hidden" name="returnUrl" value="@ViewContext.HttpContext.Request.PathAndQuery()" />
                    <span class="card-text p-1">

                        <button type="submit" class="btn btn-success btn-sm pull-right" style="float:right" asp-action="AddToCart">
                            Add to Cart
                        </button>
                    </span>
                </li>
            </ul>
        </fieldset>
    </form>


</body>

Views/Cart/CiListFiltered.cshtml
@*

    /Cart/CiListFiltered.cshtml
    uses a <select> tag to allow user to choose an item by description
    then showing the item code as output
    - This view is called from Cart controller, passes selected item to CartLineForm action method

*@
@{
    ViewData["Title"] = "Ci List Filtered ";    
    ViewData["pageTitle"] = "Catalog Items Filtered List";
}
@model List<CatalogItem>


<body>
    <div>
        <h2> @ViewBag.AmPm  This is a filtered search </h2>
        <a asp-action="Index">Back to Index</a>

        <form asp-action="CartLineForm" method="post">
            <label for="itmSelect">Select</label>
            <select id="itmSelect" name="itmSelect" onchange="{this.form.submit()}">
                @foreach (var itm in Model)
                {
                    <option class="text-dark" value="@itm.ItemId">@itm.Description</option>
                }

            </select>
        </form>

        <script>
            function myFunction() {
                var x = document.getElementById("itmSelect").value;
                document.getElementById("itemIdCheck").innerHTML = "You selected: " + x;
                //document.getElementById("itemDescr").innerHTML = document.getElementById("mySelect").;
            }
        </script>
   </div>
</body>

Views/Cart/Index.cshtml
@*
    This is not a normal Index view, it beginss the CartLine creation process
    /Cart/Index - CartController Index View requests a searchString to send to CiListFiltered action 
   
*@


@{
    ViewData["Title"] = "Cart Line Item";    
    ViewData["pageTitle"] = "Cart Line Item Filter";
}

<body>
    <div>
        <fieldset>
            <legend>Input a search word or string</legend>            
            <!-- make an input box and send filter string to ICListFilter action method in CartController -->
            <form asp-action="CiListFiltered">
                <div>
                    <p>
                        Find by: <input id="filterString" type="text" name="filterString" />
                        <input type="submit" value="Search" class="btn btn-sm" />

                    </p>
                </div>
            </form>
        </fieldset>
    </div>
</body>