Areas/Pull/Models/PullDisplayViewModel.cs
// ================================================
// PullDisplayViewModel.cs, 210516
// Author: Russell Fisher
// - the purpose of this VM is to send in a PullHdr object  
//    along with a CatalogItem Dictionary(ItemId, Description)
//    to enable Descriptions in a user view.
// =================================================

using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using SHTWIMS03.Areas.Pull.Models;
using SHTWIMS03.Pull.Models;

namespace SHTWIMS03.Areas.Pull.Models
{
    public class PullDisplayViewModel // ----------------------------------------------------------
    {
        //private PullHdr phdr;
        //private Dictionary<string, string> cikvp;
      

        public PullHdr PHdr { get; set; }

        public Dictionary<string, string> CIKVP { get; set; }

        public PullDisplayViewModel (PullHdr ph, Dictionary<string, string> keyValuePairs)
        {

            PHdr = ph;
            CIKVP = keyValuePairs;

        }
    } // eo PullDisplayViewModel ------------------------------------------------------------------
} // eo namespace

Areas/Pull/Controllers/PullAdminController.cs
//===================================================
// PullAdminController.cs, 210504
// Author: Russell Fisher
// - enable editing of PullHdr order objects
// HttpRequest class: https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.http.httprequest?view=aspnetcore-5.0
// ==================================================

using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using SHTWIMS03.Models;
using SHTWIMS03.Pull.Models;
using SHTWIMS03.Areas.Pull.Models;



namespace SHTWIMS03.Areas.Pull.Controllers
{
    [Area("Pull")]
    public class PullAdminController : Controller // ----------------------------------------------
    {
        private IPullHdrRepository pullRepo;
        private ICatalogItemRepository ciRepo;
        private Dictionary<string, string> cikvp;
        private IPullItemRepository pitemRepo;
        private Cart cart;
        private PullHdrListViewModel phlvm;

        public Dictionary<string, string> CIKVP // ------------
        {
            //set { cikvp = value; }  
            get { return cikvp; }

        } // eo CIKVP dictionary property ----------------------

        public PullAdminController(IPullHdrRepository pulls, ICatalogItemRepository ci,  IPullItemRepository pi) // -----------------------------------------------------------
        {
            pitemRepo = pi;
            pullRepo = pulls;
            ciRepo = ci;
            cikvp = ci.CatItemKVP;
            phlvm = new PullHdrListViewModel(pulls, ci);

        } // eo PullAdminContnroller class --------------------------------------------------------


        public ViewResult Index() // --------------------------------------------------------------
        {
            return View();

        } // eo default view ----------------------------------------------------------------------
        
        public IActionResult PullSelect() // --------------------------------------------------------
        {
            // the Dictionary PullOrders is a property of of IPullHdrRepository
            return View("PullSelect", pullRepo.PullOrders);

        } // eo PullEdit action method // ---------------------------------------------------------

        //[HttpPost]  * preserve a working version  
        //public ViewResult PullDisplay(int pullHdrId) // ----------------------------------------------
        //{
        //    // created a PullDisplayViewModel to send in a PullHdr and CIKVP dictionary
        //    // https://docs.microsoft.com/en-us/dotnet/api/system.web.httprequest.form?view=netframework-4.8

        //    PullHdr localPull = pullRepo.PullHdrs.FirstOrDefault(p => p.PullHdrId == pullHdrId);
        //    //var req = Request.Form["PullHdrId"];

        //    var ssn = Request.HttpContext.Session.Id;

        //    PullDisplayViewModel PDVM = new PullDisplayViewModel(localPull, CIKVP); 
        //    return View(PDVM); 

        //} //  eo PullDisplay action method -----------------------------------------------------------

        [HttpPost]
        public ViewResult PullDisplay(int pullHdrId) // ----------------------------------------------
        {
            // created a PullDisplayViewModel to send in a PullHdr and CIKVP dictionary
            // https://docs.microsoft.com/en-us/dotnet/api/system.web.httprequest.form?view=netframework-4.8

            PullHdr localPull = pullRepo.PullHdrs.FirstOrDefault(p => p.PullHdrId == pullHdrId);
            //var req = Request.Form["PullHdrId"];

            var ssn = Request.HttpContext.Session.Id;

            PullDisplayViewModel PDVM = new PullDisplayViewModel(localPull, CIKVP);
            return View(PDVM);


        } //  eo PullDisplay action method -----------------------------------------------------------


        [HttpGet]
        public ViewResult PullItemDisplay(int pullItemId) // --------------------------------------
        {

            PullItem pi = pitemRepo.PullItems.FirstOrDefault(pid => pid.PullItemId == pullItemId);

            ViewBag.Description = cikvp[pi.ItemId];
            return View(pi);

        }// eo PullItemDisplay action method ------------------------------------------------------


        [HttpPost]
        public IActionResult PullHdrChanged(PullHdr phdr) // ------------------------------------
        {
            var stat = Request.Form["phdr.Status"];
            var ssn = Request.HttpContext.Session.Id;
            
            if(phdr!=null) 
            { 
                // SavePullHdr method is member of EFPullHdrRepository.cs
                pullRepo.SavePullHdr(phdr); 
            }

            //return RedirectToAction(nameof(Pull.Controllers.PullHdrController.PullMenu));
            //RedirectToAction(string actionName, string controllerName);
            return RedirectToAction("PullMenu", "PullHdr" );

        } // eo PullHdrChanged action -------------------------------------------------------------


    } // eo PullAdminController class -------------------------------------------------------------

} // eo namespace 

Areas/Pull/Views/PullAdmin/Index.cshtml
@*
    Pull/PullAdmin/Index.cshtml, 210504

*@
@{         
    ViewData["Title"] = "PullAdmin Index";
    ViewData["pageTitle"] = "Pull Admin Index View";
}
<body>
    <h2>Pull Admin Index View</h2>

</body>

Areas/Pull/Views/PullAdmin/PullDisplay.cshtml
@*
    PullDisplay.cshtml, 210512
    Author: Russell Fisher
     shows PullHdr retrieved from repo for  editing.
    
    url path: /Views/PullAdmin/PullSelect => /PullAdmin/PullDisplay

*@

@model PullDisplayViewModel

@{

    ViewData["Title"] = "PullDisplay";
    ViewData["pageTitle"] = "Pull Display Form";
    Layout = "_Layout-Pull";
}

<div>
    <form method="post" asp-action="PullHdrChanged">

        <!--
    <input type="hidden" asp-for="PHdr.PullHdrId" value="@Model.PHdr.PullHdrId" />
        -->

        <div>
            <label ty asp-for="PHdr.PullHdrId" class="formLabel"></label>
            <input asp-for="PHdr.PullHdrId" class="formInput" readonly />
        </div>

        <div>
            <label asp-for="PHdr.LocationId" class="formLabel"></label>
            <input asp-for="PHdr.LocationId" class="formInput" readonly />
        </div>
        <div>
            <label asp-for="PHdr.PullDate" class="formLabel">Pull Date</label>
            <input asp-for="PHdr.PullDate" class="formInput" readonly />
        </div>
        <div>
            <label asp-for="PHdr.Destination" class="formLabel"></label>
            <input asp-for="PHdr.Destination" class="formInput" />
        </div>
        <div>
            <label asp-for="PHdr.Requester" class="formLabel"></label>
            <input asp-for="PHdr.Requester" class="formInput" />
        </div>
        <div>
            <label asp-for="PHdr.ReqPhone" class="formLabel"></label>
            <input asp-for="PHdr.ReqPhone" class="formInput" />
        </div>
        <div>
            <label asp-for="PHdr.ReqEmail" class="formLabel"></label>
            <input asp-for="PHdr.ReqEmail" class="formInput" />
        </div>
        <ul>
            <li>
                <!-- p773 -->
                <label asp-for="PHdr.Status" class="formLabel"></label>
                <select asp-for="PHdr.Status"
                        asp-items="@new SelectList(Enum.GetNames(typeof(StatusTerms)))">
                    <option selected value="Open"></option>
                </select>
            </li>
        </ul>
        <div>
            <label asp-for="PHdr.Comment" class="formLabel"></label>
            <input asp-for="PHdr.Comment" class="formComment" />
        </div>
        <table>
            <colgroup>
                <col style='width:10rem;'>
                <col style='width:40rem;'>
                <col style='width:5rem;'>
                <col style='width:5rem;'>
                <col style='width:20rem;'>
                <col style='width:5rem;'>

            </colgroup>

            <caption>Pull Item List</caption>
            <tr>
            <th>Item Id</th><th>Description</th><th>UoM</th><th>Qty</th><th> Comment </th> <th>&nbsp;</th>  
            </tr>


            @foreach (PullItem pitem in @Model.PHdr.PullItems)
            {
                <tr>
                    <td>@pitem.ItemId</td>
                    <td>@Model.CIKVP[pitem.ItemId]</td>
                    <td>@pitem.UoM</td>
                    <td>@pitem.QtyRequested</td>
                    <td>@pitem.Comment</td>
                    <!-- p 250 -->
                    <td>
                        <a class="btn btn-block btn-secondary"
                           asp-action="PullItemDisplay"
                           asp-controller="PullAdmin"
                           asp-route-PullHdrId="@pitem.PullHdr"
                           asp-route-PullItemId="@pitem.PullItemId">Edit</a>
                    </td>
                </tr>
            }
            <tr></tr>
        </table>

        <input class="btn btn-primary" type="submit" value="Submit Changes" />
    </form>

</div>

Areas/Pull/Views/PullAdmin/PullHdrEdit.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@model PullHdrListViewModel;


@{
    ViewData["Title"] = "PullOrder Edit";
    ViewData["PageTitle"] = "Pull Order Edit";
    Layout = "_Layout-Reg";
}

<div>




</div>

Areas/Pull/Views/PullAdmin/PullItemDisplay.cshtml
@*
    PullItemDisplay.cshtml, 210519
    - display PullItem returned from PullDisplay.cshtml view
      to enable editing of a PullHdr.PullItems PullItem object.
    - source controller = PullAdmin, source action=PullItemDisplay
*@
@{
    ViewData["Title"] = "Pull Item";
    ViewData["pageTitle"] = "Pull Item Edit Form";
}

@model PullItem

<div>
    <form method="post">
        <div>
            <label asp-for="PullItemId"></label>
            <input asp-for="PullItemId" readonly />
        </div>
        <div>
            <label asp-for="ItemId" class="formLabel"></label>
            <input asp-for="ItemId" class="formInput" />
        </div>
        <div>
            <label class="formLabel">Description</label>
            <span style="border:1px solid grey; background:white; width:14rem;">@ViewBag.Description</span>
        </div>
        <div>
            <label asp-for="UoM" class="formLabel"></label>
            <input asp-for="UoM" class="formInput" />
        </div>

        <div>
            <label asp-for="QtyRequested" class="formLabel"></label>
            <input asp-for="QtyRequested" class="formInput" />
        </div>
            
        <div>
            <label asp-for="QtyShipped" class="formLabel"></label>
            <input asp-for="QtyShipped" class="formInput" />
        </div>

        <div>
            <label asp-for="DateNeeded" class="formLabel"></label>
            <input asp-for="DateNeeded" class="formInput" />
        </div>

        <div>
            <label asp-for="Comment" class="formLabel"></label>
            <input asp-for="Comment" class="formInput" />
        </div>
    </form>
</div>

Areas/Pull/Views/PullAdmin/PullSelect.cshtml
@*
    PullSelect.cshtml, 210510
    Authos: Russell Fisher
    - display a list of pull summary strings Dictionary<int,string> to enable 
      selecting a PullHdr object for editing
    
    url = /pullAdmin/pullselect

*@
@model Dictionary<int,string>

@{
    ViewData["Title"] = "Pull Select";
    ViewData["pageTitle"] = "Select Pull Order for Editing";
    Layout = "_Layout-Pull";    
}

<div>
    <a asp-action="Index">Back to Index</a>
   
    <label> Select a Pull Order for editing </label>
    <form  asp-action="PullDisplay">
        <select name="pullHdrId" onchange="{this.form.submit()}">
            {
            <option disabled selected value="">Select a Pull Order to edit</option>
                @foreach (var pull in Model)
                {
                    <option value="@pull.Key">@pull.Value</option>
                }
            }
        </select>
    </form>
</div>